# Trading Bot Configuration
# Optimize these parameters to achieve 1% daily returns

# Trading Setup
trading:
  initial_capital: 100000
  commission: 0.001  # 0.1% commission per trade
  
# Symbols to trade (high volatility intraday stocks)
symbols:
  primary: 
    - 'TSLA'   # High volatility
    - 'AAPL'   # High volume
    - 'MSFT'   # Stable trends
    - 'GOOGL'  # Good range
    - 'NVDA'   # Tech momentum
  
  backup:
    - 'AMD'
    - 'META'
    - 'AMZN'
    - 'NFLX'

# Data Settings
data:
  period: '10d'        # Data lookback period
  interval: '5m'       # Trading timeframe (1m, 2m, 5m, 15m, 30m)
  min_bars_required: 50

# Price Action Breakout Strategy Parameters
strategy:
  price_action_breakout:
    # Core Parameters - OPTIMIZE THESE FOR 1% DAILY TARGET
    lookback_period: 20          # Support/Resistance detection period
    volume_threshold: 1.3        # Volume confirmation multiplier
    atr_period: 14              # ATR calculation period
    stop_loss_atr: 1.5          # Stop loss in ATR multiples  
    take_profit_atr: 2.5        # Take profit in ATR multiples
    min_breakout_pct: 0.3       # Minimum breakout strength %
    
    # Risk Management
    risk_per_trade: 0.02        # Risk 2% per trade
    max_position_size: 1000     # Maximum shares per position
    
    # Additional Filters
    volume_ma_period: 20        # Volume moving average
    pullback_bars: 3           # Bars to wait for pullback
    
    # Trading Hours (in Eastern Time)
    start_time: "09:30"
    end_time: "15:30"
    avoid_first_minutes: 30     # Skip first 30 min
    avoid_last_minutes: 30      # Skip last 30 min

# Backtesting Settings
backtest:
  # Test multiple parameter combinations
  optimization:
    enabled: true
    
    # Parameters to optimize for 1% daily target
    lookback_period: [15, 20, 25, 30]
    volume_threshold: [1.2, 1.3, 1.5, 1.8]
    stop_loss_atr: [1.0, 1.5, 2.0]
    take_profit_atr: [2.0, 2.5, 3.0, 3.5]
    risk_per_trade: [0.015, 0.02, 0.025, 0.03]
    
  # Performance targets
  targets:
    daily_return: 1.0          # Target 1% daily return
    max_drawdown: 5.0          # Maximum 5% drawdown
    min_win_rate: 55.0         # Minimum 55% win rate
    min_profit_factor: 1.3     # Minimum profit factor

# Performance Analytics
analytics:
  track_metrics:
    - 'total_return'
    - 'daily_return'
    - 'max_drawdown' 
    - 'win_rate'
    - 'profit_factor'
    - 'sharpe_ratio'
    - 'trades_per_day'
    
  export_results: true
  save_equity_curve: true

# Risk Management Rules
risk_management:
  # Portfolio level limits
  max_daily_loss: 3.0         # Stop trading if lose 3% in a day
  max_open_positions: 3       # Maximum concurrent positions
  
  # Position sizing rules  
  min_position_value: 1000    # Minimum $1000 per position
  max_position_value: 20000   # Maximum $20000 per position
  
  # Stop loss rules
  max_stop_distance: 3.0      # Maximum 3% stop loss
  trailing_stop: true         # Enable trailing stops

# Logging
logging:
  level: 'INFO'
  save_to_file: true
  trade_log: true
  performance_log: true

# Alerts (for future live trading)
alerts:
  enabled: false
  email: 'your.email@example.com'
  discord_webhook: null
  
# Live Trading (disabled for backtesting)
live_trading:
  enabled: false
  broker: 'paper'  # paper, alpaca, interactive_brokers
  
# Notes for optimization:
# - Start with these baseline parameters
# - Run backtests on multiple symbols
# - Optimize parameters that give consistent 1%+ daily returns
# - Focus on win rate