# 🔐 FYERS CREDENTIALS TEMPLATE
# ============================================================
# Copy this file to 'fyers_credentials.yaml' and add your real credentials
# Never commit the real credentials file to version control!

# Fyers API Credentials
# Get these from: https://myapi.fyers.in/
fyers_credentials:
  app_id: "YOUR_FYERS_APP_ID_HERE"        # Format: ABC123-100
  secret_key: "YOUR_FYERS_SECRET_KEY_HERE" # 40-character secret key
  redirect_uri: "https://127.0.0.1:8080/callback"  # Must match registered URI
  
  # Your Fyers Client ID (after first login)
  client_id: ""  # Will be generated after first authentication
  
  # Access Token (generated automatically)
  access_token: ""  # Will be refreshed automatically

# Trading Preferences
trading_preferences:
  default_product_type: "INTRADAY"    # INTRADAY, CNC, MARGIN
  auto_square_off: true               # Auto square-off at 3:20 PM
  square_off_time: "15:20"           # Time to close all positions
  
  # Risk limits
  max_daily_loss: 5000               # ₹5,000 max daily loss
  max_position_size: 50000           # ₹50,000 max per position
  max_trades_per_day: 25             # Maximum trades per day

# Paper Trading Settings (for testing)
paper_trading:
  enabled: true                      # Start with paper trading
  virtual_capital: 100000            # ₹1 Lakh virtual money
  realistic_slippage: true           # Include realistic slippage
  commission_per_trade: 20           # ₹20 brokerage per trade

# Notifications
notifications:
  order_updates: true                # Get order execution updates
  position_alerts: true              # Position P&L alerts
  daily_summary: true                # End-of-day summary

# Security Settings
security:
  session_timeout_minutes: 480       # 8 hours session timeout
  auto_logout_time: "15:30"          # Auto logout after market close
  require_totp: false                # Two-factor authentication
