# 🎯 NIFTY 50 PAPER TRADING CONFIGURATION
# ============================================================
# Safe paper trading configuration for strategy validation
# All trades are logged but not executed

# Paper Trading Mode Settings
paper_trading:
  enabled: true
  initial_capital: 100000.0  # ₹1 lakh starting capital
  log_directory: "/workspaces/Intradar-bot/data/paper_trading"
  session_timeout_hours: 8  # Max session duration
  max_trades_per_session: 100
  
# Nifty 50 Target Stocks
nifty50_symbols:
  # Top Liquid Stocks (Primary Focus)
  primary:
    - "RELIANCE.NS"    # Reliance Industries
    - "TCS.NS"         # Tata Consultancy Services  
    - "HDFCBANK.NS"    # HDFC Bank
    - "INFY.NS"        # Infosys
    - "ICICIBANK.NS"   # ICICI Bank
    - "HINDUNILVR.NS"  # Hindustan Unilever
    - "BHARTIARTL.NS"  # Bharti Airtel
    - "ITC.NS"         # ITC
    - "SBIN.NS"        # State Bank of India
    - "KOTAKBANK.NS"   # Kotak Mahindra Bank
    
  # Secondary Targets
  secondary:
    - "LT.NS"          # Larsen & Toubro
    - "HCLTECH.NS"     # HCL Technologies
    - "AXISBANK.NS"    # Axis Bank
    - "ASIANPAINT.NS"  # Asian Paints
    - "MARUTI.NS"      # Maruti Suzuki
    - "TITAN.NS"       # Titan Company
    - "WIPRO.NS"       # Wipro
    - "ULTRACEMCO.NS"  # UltraTech Cement
    - "NESTLEIND.NS"   # Nestle India
    - "BAJFINANCE.NS"  # Bajaj Finance

# Strategy Parameters (Paper Trading Optimized)
strategy:
  name: "PaperTradingBalancedBreakout"
  
  # Entry Conditions
  lookback_period: 5
  volume_threshold: 0.3
  min_breakout_pct: 0.003  # 0.3% minimum breakout
  min_rsi_spread: 10
  volume_spike_threshold: 1.3
  
  # Risk Management
  stop_loss_pct: 0.15      # 0.15% stop loss
  take_profit_pct: 0.20    # 0.20% take profit
  max_hold_bars: 8         # Max 8 minutes hold
  
  # Position Sizing
  position_size: 1500      # Default shares
  max_position_value: 50000 # ₹50,000 max per position
  
  # Trading Hours (IST)
  trade_start_hour: 9      # 9:30 AM
  trade_end_hour: 15       # 3:00 PM

# Data Configuration
data:
  provider: "yfinance"
  default_period: "2d"     # 2 days for paper testing
  default_interval: "1m"   # 1-minute bars
  
  # Alternative intervals for testing
  test_intervals:
    - "1m"   # 1-minute scalping
    - "5m"   # 5-minute swing
    - "15m"  # 15-minute position

# Paper Trading Validation Rules
validation:
  # Minimum requirements before live trading
  required_paper_trades: 50
  required_win_rate_pct: 45.0
  required_avg_trade_pnl: -50.0  # Max ₹50 avg loss allowed
  max_drawdown_pct: 10.0
  
  # Session validation
  min_trading_sessions: 5
  min_symbols_tested: 10
  min_sectors_covered: 3

# Risk Limits (Paper Trading)
risk_management:
  max_daily_trades: 20
  max_daily_loss: 5000.0      # ₹5,000 max daily loss
  max_position_risk_pct: 2.0  # 2% of capital per trade
  
  # Circuit breakers
  daily_loss_limit: 3000.0    # Stop if daily loss exceeds
  max_consecutive_losses: 5   # Stop after 5 consecutive losses

# Logging and Reporting
logging:
  trade_log_format: "json"
  csv_export: true
  performance_reports: true
  
  # Log levels
  console_level: "INFO"
  file_level: "DEBUG"
  
  # Report frequency
  summary_interval_trades: 10
  live_summary_minutes: 5

# Market Hours and Conditions
market:
  timezone: "Asia/Kolkata"
  
  # Trading sessions
  regular_hours:
    start: "09:30"
    end: "15:30"
  
  pre_market:
    start: "09:00" 
    end: "09:30"
    
  # Market holidays (paper trading can run anytime)
  skip_weekends: false
  skip_holidays: false

# Performance Tracking
tracking:
  # Metrics to calculate
  calculate_sharpe: true
  calculate_drawdown: true
  calculate_var: true
  
  # Benchmarking
  benchmark_symbol: "^NSEI"  # Nifty 50 index
  
  # Sector analysis
  track_sector_performance: true
  
# Alert Configuration  
alerts:
  # Performance alerts
  win_rate_below_pct: 40.0
  drawdown_above_pct: 8.0
  daily_loss_above: 2000.0
  
  # System alerts
  data_feed_failure: true
  strategy_errors: true
  
# Export Settings
export:
  # Auto-export after session
  auto_export_csv: true
  auto_export_json: true
  
  # Export location
  export_directory: "/workspaces/Intradar-bot/data/exports"
  
  # Include in exports
  include_performance_metrics: true
  include_trade_analysis: true
  include_sector_breakdown: true

# 🏦 FYERS BROKER CONFIGURATION (For Live Trading)
# ============================================================
# Add Fyers credentials here when ready for live trading

fyers:
  # API Credentials (Required for live trading)
  # ⚠️  Get these from Fyers Developer Portal: https://myapi.fyers.in/
  app_id: "${FYERS_APP_ID}"           # Environment variable recommended
  secret_key: "${FYERS_SECRET_KEY}"   # Environment variable recommended  
  redirect_uri: "https://127.0.0.1:8080/callback"
  
  # Trading Mode
  paper_trading: true  # Keep true for paper trading, false for live
  
  # API Configuration
  api:
    base_url: "https://api-t1.fyers.in/api/v3"  # Paper trading URL
    timeout_seconds: 30
    retry_attempts: 3
    
  # Order Settings
  orders:
    product_type: "INTRADAY"        # INTRADAY for same-day square-off
    validity: "DAY"                 # DAY validity for orders
    disclosed_qty: 0                # No quantity disclosure
    
  # Risk Management (Paper Trading Limits)
  risk:
    max_order_value: 50000          # ₹50K max per order
    max_daily_trades: 20            # Max 20 trades per day
    position_size_limit: 100000     # ₹1L total position limit
    
  # Symbol Format for Fyers API
  symbols:
    format: "NSE:{symbol}-EQ"       # NSE equity format
    
    # Pre-mapped Nifty 50 symbols for Fyers
    nifty50_fyers_format:
      "RELIANCE.NS": "NSE:RELIANCE-EQ"
      "TCS.NS": "NSE:TCS-EQ"
      "HDFCBANK.NS": "NSE:HDFCBANK-EQ"
      "INFY.NS": "NSE:INFY-EQ"
      "ICICIBANK.NS": "NSE:ICICIBANK-EQ"
      "HINDUNILVR.NS": "NSE:HINDUNILVR-EQ"
      "BHARTIARTL.NS": "NSE:BHARTIARTL-EQ"
      "ITC.NS": "NSE:ITC-EQ"
      "SBIN.NS": "NSE:SBIN-EQ"
      "KOTAKBANK.NS": "NSE:KOTAKBANK-EQ"

# Environment Variables Setup
# ============================================================
# For security, set these environment variables instead of hardcoding:
#
# Linux/Mac:
# export FYERS_APP_ID="your_app_id_here"
# export FYERS_SECRET_KEY="your_secret_key_here"
#
# Windows:
# set FYERS_APP_ID=your_app_id_here
# set FYERS_SECRET_KEY=your_secret_key_here
